import 'package:logger/logger.dart';
import 'package:test/test.dart';
import 'package:rrule/rrule.dart';

import 'daily_strategy_test.dart';
import 'monthly_strategy_test.dart';
import 'unsupported_strategy_test.dart';
import 'weekly_strategy_test.dart';
import 'yearly_strategy_test.dart';

void main() {
  Logger.level = Level.nothing;

  dailyFreqTest();
  weeklyFreqTest();
  monthlyFreqTest();
  yearlyFreqTest();
  unsupportedFreqTest();

}



// (##)DailyStrategy
//    "RRULE:FREQ=DAILY;COUNT=10"
//    "RRULE:FREQ=DAILY;UNTIL=19971224T000000Z"
//    "RRULE:FREQ=DAILY;INTERVAL=2"
//    "RRULE:FREQ=DAILY;INTERVAL=10;COUNT=5"
//    "RRULE:FREQ=DAILY;UNTIL=20000131T140000Z;BYMONTH=1"
//    "RRULE:FREQ=DAILY;UNTIL=20200523T035959Z;BYDAY=SU,MO,TU;BYMONTHDAY=-2,15"
//    "RRULE:FREQ=DAILY;UNTIL=20200523T035959Z;BYDAY=SU,MO,TU"


// (##)WeeklyStrategy
//  "RRULE:FREQ=WEEKLY;UNTIL=19971224T000000Z"
//  "RRULE:FREQ=WEEKLY;COUNT=10"
//  "RRULE:FREQ=WEEKLY;UNTIL=20200523T035959Z"
//  "RRULE:FREQ=WEEKLY;INTERVAL=2;WKST=SU"
//  "RRULE:FREQ=WEEKLY;COUNT=10;WKST=SU;BYDAY=TU,TH"
//  "RRULE:FREQ=WEEKLY;INTERVAL=2" //;BYDAY=SU,MO,WE"
//  "RRULE:FREQ=WEEKLY;INTERVAL=2;COUNT=8;WKST=SU;BYDAY=TU,TH"


// (##)MonthlyStrategy
//  "RRULE:FREQ=MONTHLY;COUNT=10;BYDAY=1FR"
//  "RRULE:FREQ=MONTHLY;INTERVAL=2;COUNT=4;BYDAY=-4TU,4SU"
//  "RRULE:FREQ=MONTHLY;INTERVAL=2;COUNT=10;BYDAY=1SU,-1SU"
//  "RRULE:FREQ=MONTHLY;COUNT=6;BYDAY=-2MO"
//  "RRULE:FREQ=MONTHLY;BYMONTHDAY=-3"
//  "RRULE:FREQ=MONTHLY;COUNT=10;BYMONTHDAY=2,15"
//  "RRULE:FREQ=MONTHLY;COUNT=10;BYMONTHDAY=1,-1"
//  "RRULE:FREQ=MONTHLY;INTERVAL=18;COUNT=10;BYMONTHDAY=10,11,12,13,14,15"
//  "RRULE:FREQ=MONTHLY;INTERVAL=2;BYDAY=TU"
//  "RRULE:FREQ=MONTHLY;BYDAY=FR;BYMONTHDAY=13"
//  "RRULE:FREQ=MONTHLY;BYDAY=SA;BYMONTHDAY=7,8,9,10,11,12,13"
//  "RRULE:FREQ=MONTHLY;COUNT=3;BYDAY=TU,WE,TH;BYSETPOS=3"
//  "RRULE:FREQ=MONTHLY;BYDAY=MO,TU,WE,TH,FR;BYSETPOS=-2"




// (##) YearlyStrategy
// RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU;UNTIL=20061029T060000Z
// RRULE:FREQ=YEARLY;BYMONTH=4;BYDAY=-1SU;UNTIL=19860427T070000Z
// RRULE:FREQ=YEARLY;BYMONTH=4;BYDAY=1SU;UNTIL=20060402T070000Z
//  RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU
//  RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU
//  RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU
// RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU