language: dart

dart:
  - 2.8.4
  - stable

dart_task:
  - test: --platform vm

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
